services:
  kurrentdb:
    image: kurrentplatform/kurrentdb:25.1.1
    container_name: kurrentdb-node
    ports:
      - 2113:2113
    environment:
      KURRENTDB_INSECURE: true
      KURRENTDB_RUN_PROJECTIONS: All
      KURRENTDB_ENABLE_ATOM_PUB_OVER_HTTP: true
    tty: true
